// @generated by hand from Prisma schema
// This file represents the existing Supabase PostgreSQL tables
// DO NOT run diesel migrations - this is schema-only

use diesel::table;

table! {
    /// User table - OAuth users from NextAuth/Supabase Auth
    users (id) {
        id -> Varchar,
        name -> Nullable<Varchar>,
        email -> Nullable<Varchar>,
        email_verified -> Nullable<Timestamptz>,
        image -> Nullable<Varchar>,
        role -> Varchar,
        ink_points -> Int4,
        terms_accepted_at -> Nullable<Timestamptz>,
        onboarding_completed_at -> Nullable<Timestamptz>,
        newsletter_opt_in_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

table! {
    /// OAuth Account (Google, GitHub, etc.)
    accounts (id) {
        id -> Varchar,
        user_id -> Varchar,
        #[sql_name = "type"]
        type_ -> Varchar,
        provider -> Varchar,
        provider_account_id -> Varchar,
        refresh_token -> Nullable<Text>,
        access_token -> Nullable<Text>,
        expires_at -> Nullable<Int4>,
        token_type -> Nullable<Varchar>,
        scope -> Nullable<Varchar>,
        id_token -> Nullable<Text>,
        session_state -> Nullable<Varchar>,
    }
}

table! {
    /// User session
    sessions (id) {
        id -> Varchar,
        session_token -> Varchar,
        user_id -> Varchar,
        expires -> Timestamptz,
    }
}

table! {
    /// Email verification tokens
    verification_tokens (identifier, token) {
        identifier -> Varchar,
        token -> Varchar,
        expires -> Timestamptz,
    }
}

table! {
    /// Chat threads
    threads (id) {
        id -> Varchar,
        title -> Nullable<Varchar>,
        user_id -> Nullable<Varchar>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

table! {
    /// Chat messages in a thread
    messages (id) {
        id -> Varchar,
        thread_id -> Varchar,
        role -> Varchar,
        content -> Text,
        created_at -> Timestamptz,
    }
}

table! {
    /// Products for the shop
    products (id) {
        id -> Varchar,
        name -> Varchar,
        description -> Varchar,
        price -> Numeric,
        point_price -> Int4,
        image -> Nullable<Varchar>,
        category -> Varchar,
        is_rare -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

table! {
    /// Purchase orders
    orders (id) {
        id -> Varchar,
        user_id -> Varchar,
        product_id -> Varchar,
        status -> Varchar,
        created_at -> Timestamptz,
    }
}

table! {
    /// User marginalia (notes/fragments)
    marginalia (id) {
        id -> Varchar,
        content -> Text,
        tags -> Array<Varchar>,
        user_id -> Varchar,
        likes -> Int4,
        created_at -> Timestamptz,
    }
}

table! {
    /// Blog post embeddings for RAG
    embeddings (id) {
        id -> Varchar,
        slug -> Varchar,
        content -> Text,
        metadata -> Jsonb,
        // vector column is Unsupported in Diesel, use raw SQL if needed
        locale -> Varchar,
        content_type -> Varchar,
        created_at -> Timestamptz,
    }
}

table! {
    /// Newsletter subscriptions
    newsletter_subscriptions (id) {
        id -> Varchar,
        email -> Varchar,
        status -> Varchar,
        user_id -> Nullable<Varchar>,
        confirm_token_hash -> Nullable<Varchar>,
        unsubscribe_token_hash -> Nullable<Varchar>,
        confirmed_at -> Nullable<Timestamptz>,
        unsubscribed_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::joinable!(accounts -> users (user_id));
diesel::joinable!(sessions -> users (user_id));
diesel::joinable!(threads -> users (user_id));
diesel::joinable!(messages -> threads (thread_id));
diesel::joinable!(orders -> users (user_id));
diesel::joinable!(orders -> products (product_id));
diesel::joinable!(marginalia -> users (user_id));
diesel::joinable!(newsletter_subscriptions -> users (user_id));

diesel::allow_tables_to_appear_in_same_query!(
    users,
    accounts,
    sessions,
    verification_tokens,
    threads,
    messages,
    products,
    orders,
    marginalia,
    embeddings,
    newsletter_subscriptions,
);
